version: '3.6'

services:
  api:
    build: ./app
    depends_on:
      - db
    environment:
      STAGE: test
    env_file: database.conf
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app/app
    restart: always

  db:
    env_file: database.conf
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data